services:
  secondchanceshop:
    image: ${DOCKER_USER}/secondchanceshop_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg-database:5432/SCSDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - secondchanceshop-network
networks:
  secondchanceshop-network: