services:
  secondchanceshop:
    container_name: secondchanceshop_app
    image: ${DOCKER_USER}/secondchanceshop_app:latest
    ports:
      - '8080:8080'
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:5432/SCSDB
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_HOST=scs-redis
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    labels:
      - io.portainer.accesscontrol.restricted
      - io.portainer.accesscontrol.teams=second-chance-shop
    networks:
      - secondchanceshop-network

networks:
  secondchanceshop-network:
    name: secondchanceshop-networks
    external: true
    
