version: "3.8"
services:
  pg-database:
    image: postgres:latest
    container_name: pg_database
    restart: always
    environment:
      POSTGRES_DB: SCSDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    networks:
      - secondchanceshop-network

  pgadmin4:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: tohka@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050
    networks:
      - secondchanceshop-network

  secondchanceshop:
    container_name: secondchanceshop_app
    image: hieunmse160501/secondchanceshop_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg-database:5432/SCSDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - secondchanceshop-network

  redis:
    image: redis:latest
    restart: always
    container_name: redis_container
    ports:
      - 6379:6379
    networks:
      - secondchanceshop-network

networks:
  secondchanceshop-network:
