on:
  push:
    branches:
      - main

jobs:
  build-application:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Build Image And Push
        run: docker compose build secondchanceshop && docker compose push secondchanceshop
  
  deploy-application:
    name: Deploy Application
    runs-on: arisa-server
    needs: build-application
    env:
      DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
      DB_HOST: ${{secrets.DB_HOST}}
      DB_USERNAME: ${{secrets.DB_USERNAME}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Stop API
        run: docker compose -f docker-compose.prod.yaml -p secondchanceshop-api down secondchanceshop --rmi all
        continue-on-error: true
      - name: Deploy API
        run: docker compose -f docker-compose.prod.yaml -p secondchanceshop-api up -d secondchanceshop
